my-properties:
  property:
    crossOrigin: "http://localhost:3000"
spring:
  datasource:
    url: jdbc:h2:mem:crud
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
